<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="29258" started-at="2021-05-10T13:42:26 CST" finished-at="2021-05-10T13:42:56 CST">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="29258" started-at="2021-05-10T13:42:26 CST" finished-at="2021-05-10T13:42:56 CST">
      <class name="com.lzh.jmeter.ui.cases.LoginTest">
        <test-method status="PASS" signature="initDriver()[pri:0, instance:com.lzh.jmeter.ui.cases.LoginTest@4df828d7]" name="initDriver" is-config="true" duration-ms="18" started-at="2021-05-10T13:42:32 CST" finished-at="2021-05-10T13:42:32 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="PASS" signature="login()[pri:0, instance:com.lzh.jmeter.ui.cases.LoginTest@4df828d7]" name="login" duration-ms="12521" started-at="2021-05-10T13:42:32 CST" finished-at="2021-05-10T13:42:44 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="test1()[pri:0, instance:com.lzh.jmeter.ui.cases.LoginTest@4df828d7]" name="test1" duration-ms="10032" started-at="2021-05-10T13:42:45 CST" finished-at="2021-05-10T13:42:55 CST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[aa与bb不相等 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: aa与bb不相等 expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.lzh.jmeter.ui.cases.LoginTest.test1(LoginTest.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at com.lzh.jmeter.ui.cases.LoginTest.main(LoginTest.java:28)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- com.lzh.jmeter.ui.cases.LoginTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
